[package]
name = "multiquiz-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rouille = "3.6.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "2.5.0"
default-features = false
features = ["tokio-sync"]
